version: "3.7"

services:

  tp3-db:
    image: postgres:13-alpine
    container_name: tp3-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tp3-db
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8000:8080
    depends_on:
      - tp3-db