// <auto-generated />
using System;
using WSTP3.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace WSTP3.Migrations
{
    [DbContext(typeof(TP3DBContext))]
    [Migration("20210924081011_CreationBDFilmRating")]
    partial class CreationBDFilmRating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Relational:Collation", "en_US.utf8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WSTP3.Models.EntityFramework.Compte", b =>
                {
                    b.Property<int>("CompteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CPT_ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("char(5)")
                        .HasColumnName("CPT_CP");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateTime(2021, 9, 24, 10, 10, 11, 276, DateTimeKind.Local).AddTicks(8455))
                        .HasColumnName("CPT_DATECREATION");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("CPT_LATITUDE");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("CPT_LONGITUDE");

                    b.Property<string>("Mel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CPT_MEL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CPT_NOM");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("France")
                        .HasColumnName("CPT_PAYS");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CPT_PRENOM");

                    b.Property<string>("Pwd")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("CPT_PWD");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CPT_RUE");

                    b.Property<string>("TelPortable")
                        .HasColumnType("char(10)")
                        .HasColumnName("CPT_TELPORTABLE");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CPT_VILLE");

                    b.HasKey("CompteId");

                    b.HasIndex("Mel")
                        .IsUnique();

                    b.ToTable("T_E_COMPTE_CPT");
                });

            modelBuilder.Entity("WSTP3.Models.EntityFramework.Favori", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("FLM_ID");

                    b.Property<int>("CompteId")
                        .HasColumnType("integer")
                        .HasColumnName("CPT_ID");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FAV_COMMENTAIRE");

                    b.Property<int?>("Compte")
                        .HasColumnType("integer");

                    b.Property<int?>("Film")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "CompteId")
                        .HasName("PK_FAV");

                    b.HasIndex("CompteId");

                    b.ToTable("T_J_FAVORI_FAV");
                });

            modelBuilder.Entity("WSTP3.Models.EntityFramework.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FLM_ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateParution")
                        .HasColumnType("date")
                        .HasColumnName("FLM_DATEPARUTION");

                    b.Property<decimal>("Duree")
                        .HasColumnType("numeric")
                        .HasColumnName("FLM_DUREE");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("FLM_GENRE");

                    b.Property<string>("Synopsys")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FLM_SYNOPSIS");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FLM_TITRE");

                    b.Property<string>("UrlPhoto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("FLM_URLPHOTO");

                    b.HasKey("FilmId");

                    b.ToTable("T_E_FILM_FLM");
                });

            modelBuilder.Entity("WSTP3.Models.EntityFramework.Favori", b =>
                {
                    b.HasOne("WSTP3.Models.EntityFramework.Compte", "CompteFavori")
                        .WithMany("FavorisCompte")
                        .HasForeignKey("CompteId")
                        .HasConstraintName("FK_FAV_CPT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WSTP3.Models.EntityFramework.Film", "FilmFavori")
                        .WithMany("FavorisFilm")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK_FAV_FLM")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompteFavori");

                    b.Navigation("FilmFavori");
                });

            modelBuilder.Entity("WSTP3.Models.EntityFramework.Compte", b =>
                {
                    b.Navigation("FavorisCompte");
                });

            modelBuilder.Entity("WSTP3.Models.EntityFramework.Film", b =>
                {
                    b.Navigation("FavorisFilm");
                });
#pragma warning restore 612, 618
        }
    }
}
